[package]
name = "so2lar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
env_logger = "0.11.5"
julian = { version = "0.5.0", features = ["cli", "chrono"] }
log = "0.4.22"
